### ISSUE TITLE
1. Char Pointer Not Returning Address

### ISSUE THREAD

**Issue by madhavanand-github** [madhavanand-github/Apna-College-Cpp-Course#1]
**WANT** - Explanation that why output is not returning  address in hexadecimal.
**REPOSITORY LINK** - [Click Here](https://github.com/madhavanand-github/Apna-College-Cpp-Course/blob/master/11.%20Pointers/pointerArtithmetic.cpp)
<br>
![Code Snippet](https://user-images.githubusercontent.com/57529334/98621505-66323900-232d-11eb-8b09-1f0fde29e54f.png)

**Comment by avinal** [comment]
This is simple, in `char * charPTR` charPTR can be thought of as a pointer to the first char in the array. And `std::cout` treats `char *` as a null-terminated string, hence it tries to print this string. This can be proved as when you are print `++charPTR` nothing is printed, that is actually the null char is printed. You can cast char pointer to print the address it is pointing to as below. 
```cpp
std::cout << (void *) charPTR <<std::endl;
```
P.S. - Pointers are designed a `void *` type in C/C++.

**Comment by madhavanand-github** [comment]
Awesome, it worked 💯 

In nutshell, we have to cast char pointer to `(void *)` in order to print the address.
This is because  `std::cout `treats `char *` as a null-terminated string.

Thanks a ton !!

**Comment by madhavanand-github** [comment]
**Repository** **Updated** ☑️ 
Giving the desired output. 💯 
Thanks @avinal :)

![Issue_1_Solved](https://user-images.githubusercontent.com/57529334/98774801-c1d5f280-2411-11eb-9f63-83cbc969f960.png)
